### PR TITLE
Fix bugs of CCW and make Hungarian Revolution Events end historically

### PR DESCRIPTION
**Pull request by bobliu0424**
add remove_ideas = CHI_disorganized_military2 to fix problems if you hold shanghai and get a weakened debuff but this debuff can't be removed
Reset the KMT China's Capital to Nanking, since it is more historically as their Capital
https://github.com/swf541/ColdWarIronCurtain/commit/b4f7bce51aaf3ce4ca58421c2c58bedd30a7809a

Make sure Hungarian Revolution Events went historically when go historical path
https://github.com/swf541/ColdWarIronCurtain/commit/e4df173c39ddb51b165d37c37aaebb1502d9a795

Small fixes of text, from Old Taiwan dollar to Old Chinese dollars
https://github.com/swf541/ColdWarIronCurtain/commit/c5b84492386a23f538f509224161f9e0b3210e38

### CODE REVIEW

**Comment by leftwinglow** [comment]
This is too big - We don't want the disorganised military thing to change. If you cut down your pull requests into smaller chunks we will merge them.

**Comment by bobliu0424** [comment]
> This is too big - We don't want the disorganised military thing to change. If you cut down your pull requests into smaller chunks we will merge them.

OK, I'll cut down it into at least 3 chunks: Hungarian_Revolution.txt, focus_KMT_50s_victory_l_english.yml, and PRC_scripted_effects.txt
(maybe also the 4th chunk of ROC_50s.txt to make the main political branch only available when lose civil war instead of winning in Shanghai?)

But before it, I want to ask that why CHI_disorganized_military2 idea keep after civil war, when CHI get another debuff of Military_Disorganization_modifier?

**Comment by leftwinglow** [comment]
> But before it, I want to ask that why CHI_disorganized_military2 idea keep after civil war, when CHI get another debuff of Military_Disorganization_modifier?

Can't they get rid of this debuff in their victory focus tree?

**Comment by bobliu0424** [comment]
https://github.com/swf541/ColdWarIronCurtain/pull/105#issuecomment-895113572
> Can't they get rid of this debuff in their victory focus tree?

Well, nope, despite they can reduce the debuff of Military_Disorganization_modifier(which gain from victory the whole civil war, and still remain some of debuff when run out of the tree), but about the idea of CHI_disorganized_military2, which they get it from Victory in Shanghai Campaign, it seems noway to get rid of it.

**Comment by leftwinglow** [comment]
> Well, nope, despite they can reduce the debuff of Military_Disorganization_modifier(which gain from victory the whole civil war, and still remain some of debuff when run out of the tree), but about the idea of CHI_disorganized_military2, which they get it from Victory in Shanghai Campaign, it seems noway to get rid of it.

I see, ideally they should get rid of it as some part of their focus tree, towards the end of the 1950s. You could add this if you like, it would help us out.

**Comment by bobliu0424** [comment]
> I see, ideally they should get rid of it as some part of their focus tree, towards the end of the 1950s. You could add this if you like, it would help us out.

OK, then I'll remove CHI_disorganized_military2 at the end of civil war for now (since CHI_disorganized_military is also removed here if not replaced by CHI_disorganized_military2 in Shanghai Campaign)

And this poll request will be close with this comment, smaller chunks poll request will be SOON create ^_^

**Pull request closed without merging**
